version: "3.8"

services:
  nctcdash:
    build: .
    container_name: nctcdash
    restart: unless-stopped
    expose:
      - "8501"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nctcdash.rule=Host(`analytics.nctc-dashboard.ng`)"
      - "traefik.http.routers.nctcdash.entrypoints=websecure"
      - "traefik.http.routers.nctcdash.tls.certresolver=letsencrypt"
      - "traefik.http.services.nctcdash.loadbalancer.server.port=8501"

networks:
  traefik-proxy:
    external: true
